# base image
FROM python:3.7.0-alpine

# new
# install dependencies
RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd

# set working directory
WORKDIR /usr/src/app

# install poetry
RUN pip install poetry ; \
    poetry config settings.virtualenvs.create false

# add entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh

# add app
COPY . /usr/src/app

# install dependencies
RUN poetry install

# run server
CMD ["/usr/src/app/entrypoint.sh"]
